AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/LineLength:
  Max: 132
Metrics/MethodLength:
  Severity: warning

# Rationale: allow Weirich-style blocks
Style/BlockDelimiters:
  Enabled: false

# Needed since core extensions might get included from `module_eval` contexts.
Style/ClassAndModuleChildren:
  Enabled: false

Style/DateTime:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

inherit_from: .rubocop_todo.yml
