sudo: false
language: ruby

# Dummy version to avoid wasting time on RVM installs.
rvm: 1.9.3

env:
 - "JRUBY_OPTS=--debug"

before_install:
 - rm -rf ~/.rvm && if [ ! -d "$HOME/jruby-bin" ]; then mkdir -p ~/jruby-bin && pushd ~/jruby-bin && curl -o- -L https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.1.15.0/jruby-dist-9.1.15.0-bin.tar.gz | tar xzf - --strip-components=1 && popd ; fi
 - export PATH="$HOME/jruby-bin/bin:$PATH"
 - gem install bundler

cache: bundler
